# Generated by Django 3.2.7 on 2021-11-15 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_auto_20211115_2310'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
