# Generated by Django 3.2.7 on 2021-11-16 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(max_length=45, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['id_category'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_city', models.AutoField(primary_key=True, serialize=False)),
                ('name_city', models.CharField(max_length=45, verbose_name='City')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'ordering': ['id_city'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('licence_plate', models.CharField(max_length=6, verbose_name='Licence Plate')),
                ('passengers', models.IntegerField(verbose_name='Passengers')),
                ('transmission', models.CharField(choices=[('A', 'Automatic'), ('M', 'Mechanical')], default='A', max_length=1, verbose_name='Transmission')),
                ('air_conditioning', models.BooleanField(verbose_name='Air Conditioning')),
                ('suitcase', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('B', 'Big')], default='S', max_length=1, verbose_name='Suitcase')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('brand', models.CharField(max_length=45, verbose_name='Brand')),
                ('model', models.CharField(max_length=45, verbose_name='Model')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carApp.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carApp.city')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'db_table': 'cars',
                'ordering': ['id_car'],
            },
        ),
    ]
