# Generated by Django 3.2.7 on 2021-11-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='licence_plate',
            field=models.CharField(max_length=6, unique=True, verbose_name='Licence Plate'),
        ),
    ]
