# Generated by Django 3.2.7 on 2021-11-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0002_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_aviability',
            field=models.BooleanField(default=True),
        ),
    ]
