# Generated by Django 3.2.7 on 2021-11-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0004_rename_is_aviability_availability_is_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='key_field',
            field=models.CharField(default='', max_length=20, verbose_name='Key Field'),
            preserve_default=False,
        ),
    ]
