# Generated by Django 3.2.7 on 2021-11-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0005_availability_key_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='key_field',
            field=models.CharField(max_length=20, unique=True, verbose_name='Key Field'),
        ),
    ]
